site_name: MZmine 3 Documentation
site_url: https://mzmine.github.io/mzmine_documentation/
edit_uri: https://github.com/mzmine/mzmine_documentation/edit/master/docs/
repo_name: mzmine/mzmine_documentation
repo_url: https://github.com/mzmine/mzmine_documentation
use_directory_urls: false

nav:
  - Home page: index.md
  - Main window overview: Main-window-overview.md
  - LC-MS workflow: workflows/lcmsworkflow/lcms-workflow.md
  - LC-IMS-MS workflow: workflows/imsworkflow/Ion-mobility-data-processing-workflow.md
  - Module documentations:
      - Data import: module_docs/dataimport/data-import.md
      - Mass detection: module_docs/massdetection/mass-detection.md
      - Mobility scan merging: module_docs/mobilityscanmerging/mobility-scan-merging.md
      - ADAP Chromatogram builder: module_docs/adapchromatogrambuilder/adap-chromatogram-builder.md
      - Ion mobility expander: module_docs/imsexpander/ims-expander.md
      - Ion mobility trace builder: module_docs/ionmobilitytracebuilder/ion-mobility-trace-builder.md
      - Smoothing: module_docs/smoothing/smoothing.md
      - Resolving: module_docs/localminimumresolver/local-minimum-resolver.md
      - CCS calibration: module_docs/ccs_calibration/ccs_calibration.md
  - Visualisation:
      - Raw data visualisation: Raw-data-visualisation.md
  - Additional IMS resources:
      - Terminology: workflows/imsworkflow/ion-mobility-spectrometry-terminology.md
      - Data format insight: workflows/imsworkflow/lc-ms-and-lc-ims-ms-data-comparison.md
  - Performance options: performance.md
  - Contribute: Contribute.md
  - Acknowledgements: wikiacknowledgements.md

theme:
  name: material

plugins:
  - search
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      type: datetime
  - with-pdf:
      output_path: documentation.pdf
      author: The MZmine Community
      cover_title: MZmine 3
      cover_subtitle: Documentation
      cover_logo: img/MZmine_logo_CMYK.eps

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
