site_name: MZmine 3 Documentation
site_url: https://mzmine.github.io/mzmine_documentation/
edit_uri: https://github.com/mzmine/mzmine_documentation/edit/master/docs/
repo_name: mzmine/mzmine_documentation
repo_url: https://github.com/mzmine/mzmine_documentation
use_directory_urls: false

nav:
  - Home page: index.md
  - Getting started: getting_started.md
  - Main window overview: main-window-overview.md

  - Processing modules:
      - I/O:
          -  Data import: module_docs/io/data-import.md
          -  Data export: module_docs/io/data-export.md
#         TODO Add feature list import/export
      - File merging:
        - Raw data files merging: module_docs/featdet_file_merging/raw-files-merging.md
        - Mobility scan merging: module_docs/featdet_mobility_scan_merging/mobility-scan-merging.md
      - Raw data filtering:
          - Scan by scan filtering: module_docs/filter_raw_data/filter-scan-by-scan.md
          - Crop filter: module_docs/filter_raw_data/crop-filter.md
          - Baseline corrections: module_docs/filter_raw_data/baseline-corrections.md
          - Align scans: module_docs/filter_raw_data/align-scans.md
          - Scan smoothing: module_docs/filter_raw_data/scan_smoothing.md
      - Mass detection:
        - Mass detection: module_docs/featdet_mass_detection/mass-detection.md
        - Mass detection algorithms: module_docs/featdet_mass_detection/mass-detection-algorithms.md
        - FTMS shoulder peak finder: module_docs/featdet_mass_detection/FTMS-shoulder-peak-filter.md
        - Mass calibration: module_docs/featdet_mass_detection/mass-calibration.md
      - LC-MS feature detection:
        - ADAP Chromatogram builder: module_docs/lc-ms_featdet/featdet_adap_chromatogram_builder/adap-chromatogram-builder.md
        - GridMass: module_docs/lc-ms_featdet/featdet_gridmass/gridmass.md
        - Targeted feature detection: module_docs/lc-ms_featdet/targeted_featdet/targeted-featdet.md
      - LC-IMS-MS feature detection:
        - Ion mobility expander: module_docs/lc-ims-ms_featdet/featdet_ims_expander/ims-expander.md
        - Ion mobility trace builder: module_docs/lc-ims-ms_featdet/featdet_ion_mobility_trace_builder/ion-mobility-trace-builder.md
        - Recursive IMS builder: module_docs/lc-ims-ms_featdet/recursive_ims_builder/recursive-ims-builder.md
      - Smoothing: module_docs/featdet_smoothing/smoothing.md
      - Resolving: module_docs/featdet_resolver_local_minimum/local-minimum-resolver.md
#      TODO Update resolving
#      TODO Add mobilogram binning
      - CCS calibration: module_docs/id_ccs_calibration/ccs_calibration.md
      - MS2 scan pairing: module_docs/featdet_ms2_scan_pairing/ms2_scan_pairing.md
      - Isotope filtering:
          - 13C isotope filter (isotope grouper): module_docs/filter_isotope_filter/isotope_filter.md
          - Isotope pattern finder: module_docs/filter_isotope_finder/isotope_finder.md
          - Isotope peak scanner: module_docs/filter_isotope_peak_scanner/isotope_peak_scanner.md
#      TODO Add feature grouping
      - Spectral deconvolution (GC):
        - Hierarchical clustering: module_docs/featdet_hierarch_clustering/featdet_hierarch_clustering.md
        - Multivariate curve resolution: module_docs/featdet_multivariate_curve_res/featdet_multivar_curve_res.md
      - Feature list filtering:
        - Duplicate feature filter: module_docs/filter_duplicate_features/duplicate_feature_filter.md
        - Feature list rows filter: module_docs/feature_list_row_filter/feature_list_rows_filter.md
        - Feature filter: module_docs/feature_filter/feature_filter.md
        - Peak comparison rows filter: module_docs/filter_peakcomparison_row_filter/filter_peakcomparison_row_filter.md
        - Neutral loss filter: module_docs/filter_neutral_loss/filter_neutral_loss.md
        - m/z mobility region extraction: module_docs/filter_mobilitymzregionextraction/filter_mobilitymzregionextraction.md
        - Feature list blank subtraction: module_docs/filter_blanksubtraction/filter_blanksubtraction.md
      - Alignment:
          - Join aligner: module_docs/align_join_aligner/join_aligner.md
          - Merge lists: module_docs/align_merge_lists/align_merge_lists.md
          - RANSAC aligner: module_docs/align_ransac/align_ransac.md
          - Hierachical aligner (GC): module_docs/align_hierarch/align_hierarch.md
          - ADAP aligner (GC): module_docs/align_adap/align_adap_gc.md
          - LC Image Aligner: module_docs/align_lc-image/align_lc-image.md
      - Gap filling:
        - Peak finder: module_docs/gapfill_peak_finder/gap-filling.md
        - Same RT and m/z range gap filler: module_docs/gapfill_same_mz_and_RT_range/same_mz_and_RT_range_gap_filler.md
      - Spectral library creation: module_docs/id_spectral_library_creation/spectral_library_creation.md
      - Spectral library search: module_docs/id_spectral_library_search/spectral_library_search.md
      - Export to GNPS-FBMN/IIMN: module_docs/GNPS_export/gnps_export.md
      - Other parameters:
        - Merge MS/MS: module_docs/GNPS_export/merge_ms2_kai.md
        - Spectra similarity: module_docs/align_join_aligner/spectra_similarity.md

  - Visualization modules:
      - Visualization overview: visualization_modules/visualization_overview/visualization-overview.md
      - MS data visualisation:
          - Raw data overview: visualization_modules/raw_data_overview/raw_data_overview.md
          - Additional tools:  visualization_modules/raw_data_overview/raw_data_additional.md
      - Ion mobility data visualisation:  visualization_modules/ims_raw_data_overview/IM-data-visualisation.md
      - Image viewer: visualization_modules/image_raw_data/image_viewer.md
      - Processed data visualition:
          - MSMS Visualizer: visualization_modules/msmsplot/msms-plot.md
          - Interactive Ion Identity Molecular Networks: visualization_modules/interactive_ion_id_netw/interactive_ion_id_netw.md
          - Feature histograms: visualization_modules/feature_histograms/feature_hist.md
          - Additional tools: visualization_modules/processed_additional/processed_additional.md

  - Workflows:
      - LC-MS workflow: workflows/lcmsworkflow/lcms-workflow.md
      - LC-IMS-MS workflow: workflows/imsworkflow/ion-mobility-data-processing-workflow.md
      - Batch processing: workflows/batch_processing/batch-processing.md

  - Additional resources:
      - General Terminology: terminology/general-terminology.md
      - IMS Terminology: terminology/ion-mobility-terminology.md
      - LC-MS and LC-IMS-MS data comparison: workflows/imsworkflow/lc-ms-and-lc-ims-ms-data-comparison.md
      
  - Performance options: performance.md
  - Command line tool (batch mode): commandline_tool.md
  - Contribute:
    - Contribute: contribute.md
    - MZmine development (in IntelliJ): contribute_intellij.md

  - Acknowledgements: wikiacknowledgements.md

copyright: This documentation is licensed under the MIT License (MIT). 

theme:
  name: material
  logo: img/MZMine_logo_white.png

plugins:
  - search
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      type: datetime
#  - with-pdf:
#      output_path: documentation.pdf
#      author: The MZmine Community
#      cover_title: MZmine 3
#      cover_subtitle: Documentation
#      cover_logo: img/MZmine_logo_CMYK.png

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  #   https://squidfunk.github.io/mkdocs-material/reference/formatting/
  #   superscript ^13^C subscript H~2~O
  #   key combinations: ++ctrl+alt+del++
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
